CREATE DATABASE FABRICACAO;
USE FABRICACAO;

CREATE TABLE PROCESSO (
	COD_PROCESSO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL
);

CREATE TABLE PRODUTO (
	COD_PRODUTO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(20) NOT NULL UNIQUE,
    TIPO CHAR(1) NOT NULL, 
    COD_PROCESSO INTEGER NOT NULL,
    
    FOREIGN KEY (COD_PROCESSO) REFERENCES PROCESSO(COD_PROCESSO)
);

CREATE TABLE COMPOSICAO (
	COD_PRODUTO INTEGER NOT NULL,
    COD_COMPONENTE INTEGER NOT NULL,
    QUANTIDADE DOUBLE NOT NULL,
    
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO),
    FOREIGN KEY (COD_COMPONENTE) REFERENCES PRODUTO (COD_PRODUTO)
);

CREATE TABLE FORNECEDOR (
	COD_FORNECEDOR INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE COMPRADO_NO (
	COD_PRODUTO INTEGER NOT NULL,
    COD_FORNECEDOR INTEGER NOT NULL,
    PRAZO_ENTREGA VARCHAR(20) NOT NULL,
    
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR (COD_FORNECEDOR)
);

CREATE TABLE TAREFA (
	COD_TAREFA INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TEMPO VARCHAR(20) NOT NULL,
    NOME VARCHAR(20) NOT NULL 
);

CREATE TABLE ORDEM_EXECUCAO (
	COD_PROCESSO INTEGER NOT NULL,
    COD_TAREFA INTEGER NOT NULL,
    ORDEM INTEGER NOT NULL,
    
    FOREIGN KEY(COD_PROCESSO) REFERENCES PROCESSO(COD_PROCESSO),
    FOREIGN KEY(COD_TAREFA) REFERENCES TAREFA(COD_TAREFA)
);






